--Tanner Ellenberger
--Nick Gay
--DeMarcus George
--Joel Myambayi

--A10P4

--1
Select F.PILOT_KEY, P.EMP_LNAME, P.EMP_FNAME, MAX(F.CHAR_DISTANCE) AS [Max Distance Flown(In Miles)]
From FACT F INNER JOIN PILOTDIM P On F.PILOT_KEY = P.PILOT_KEY
Group By F.PILOT_KEY, P.EMP_LNAME, P.EMP_FNAME
Order By  [Max Distance Flown(In Miles)] DESC

--2
SELECT  A.MOD_CODE, MONTH(T.CHAR_MONTH) AS [CHARTER MONTH], SUM(F.CHAR_DISTANCE * F.MOD_CHG_MILE) AS [REVENUE]
FROM AIRCRAFTDIM A INNER JOIN FACT F ON A.AIRCRAFT_KEY = F.AIRCRAFT_KEY
	 INNER JOIN TIMEDIM T ON F.TIME_KEY = T.TIME_KEY
GROUP BY A.MOD_CODE, T.CHAR_MONTH
ORDER BY [REVENUE] DESC



	  